language: ruby
before_install:
  - gem update bundler
matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-3.X
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-4.0
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-4.2
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-3.X
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-4.0
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-4.2
    - rvm: 2.1.0
      gemfile: gemfiles/Gemfile.rails-3.X
    - rvm: 2.1.0
      gemfile: gemfiles/Gemfile.rails-4.0
    - rvm: 2.1.0
      gemfile: gemfiles/Gemfile.rails-4.2
    - rvm: 2.2.2
      gemfile: gemfiles/Gemfile.rails-4.2
    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.rails-4.0
    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.rails-4.2

  fast_finish: true
  allow_failures:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-4.0
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-4.2
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-4.2
    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.rails-3.0

